import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../providers/tracking_provider.dart';
import '../providers/permission_provider.dart';
import '../widgets/empty_state.dart';
import '../widgets/status_indicator.dart';
import '../widgets/floating_control_button.dart';
class TrackingPage extends StatefulWidget { const TrackingPage({super.key}); @override State<TrackingPage> createState() => _TrackingPageState(); }
class _TrackingPageState extends State<TrackingPage> { @override void initState() { super.initState(); WidgetsBinding.instance.addPostFrameCallback((_) => context.read<TrackingProvider>().start()); } @override void dispose() { context.read<TrackingProvider>().stop(); super.dispose(); }
@override Widget build(BuildContext context) { final tracking = context.watch<TrackingProvider>(); final ready = context.watch<PermissionProvider>().ready; final gaze = tracking.latest; if (!ready) return const Scaffold(body: EmptyState(icon: Icons.lock_outline_rounded, title: 'أكمل الصلاحيات', subtitle: 'فعّل متطلبات النظام قبل بدء التتبع.')); if (gaze == null) return Scaffold(appBar: AppBar(title: const Text('تتبع النظر')), floatingActionButton: FloatingControlButton(active: tracking.running, onPressed: tracking.running ? tracking.stop : tracking.start), body: const EmptyState(icon: Icons.visibility_off_outlined, title: 'في انتظار بيانات النظر', subtitle: 'تأكد من تشغيل الكاميرا ثم ابقَ أمام الشاشة.')); final confidence = gaze.confidence.clamp(0.0,1.0); return Scaffold(appBar: AppBar(title: const Text('تتبع النظر'), actions: [Padding(padding: const EdgeInsetsDirectional.only(end:18), child: Center(child: StatusIndicator(active: !gaze.isBlinking, label: gaze.isBlinking ? 'رمشة' : 'نشط')))]), floatingActionButton: FloatingControlButton(active: tracking.running, onPressed: tracking.running ? tracking.stop : tracking.start), body: ListView(padding: const EdgeInsets.fromLTRB(20,8,20,110), children: [Card(child: SizedBox(height:260, child: Stack(children: [Center(child: Icon(Icons.visibility_rounded,size:84,color:Theme.of(context).colorScheme.primary.withOpacity(.16))), Center(child: Container(width:150,height:150,decoration:BoxDecoration(shape:BoxShape.circle,border:Border.all(color:Theme.of(context).colorScheme.primary.withOpacity(.22),width:2)),child:Center(child:Text(gaze.isBlinking ? 'BLINK':'TRACKING',style:Theme.of(context).textTheme.labelLarge?.copyWith(fontWeight:FontWeight.w800)))))]))), const SizedBox(height:14), Row(children: [Expanded(child: _MetricCard(label:'X',value:gaze.xPx.toStringAsFixed(0),unit:'px')), const SizedBox(width:10), Expanded(child:_MetricCard(label:'Y',value:gaze.yPx.toStringAsFixed(0),unit:'px'))]), const SizedBox(height:10), _MetricCard(label:'الثقة',value:(confidence*100).toStringAsFixed(0),unit:'%'), const SizedBox(height:18), LinearProgressIndicator(value:confidence,minHeight:8,borderRadius:BorderRadius.circular(8)), const SizedBox(height:8), Text('جودة الإشارة',style:Theme.of(context).textTheme.bodySmall)])); }
}
class _MetricCard extends StatelessWidget { const _MetricCard({required this.label,required this.value,required this.unit}); final String label; final String value; final String unit; @override Widget build(BuildContext context)=>Card(child:Padding(padding:const EdgeInsets.all(16),child:Row(children:[Text(label,style:Theme.of(context).textTheme.labelLarge),const Spacer(),Text(value,style:Theme.of(context).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.w800)),const SizedBox(width:5),Text(unit,style:Theme.of(context).textTheme.bodySmall)]))); }
